//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallEnquiry
    {
        public int Id { get; set; }
        public string cname { get; set; }
        public string cmobile { get; set; }
        public string cpattern { get; set; }
        public string cspec { get; set; }
        public string cqty { get; set; }
        public string cventure { get; set; }
        public Nullable<System.DateTime> rts { get; set; }
    }
}
