//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReportingTbl
    {
        public int Id { get; set; }
        public string LoomNo { get; set; }
        public string OwnParty { get; set; }
        public string QualityNo { get; set; }
        public string ReedxPickxRs { get; set; }
        public string BeamNo { get; set; }
        public string BeamPipeNo { get; set; }
        public string DateOfGaitingKnotting { get; set; }
        public string BillFallDate { get; set; }
        public string Nos { get; set; }
        public string AvgOfRollingMtr { get; set; }
        public string AvgOfPick { get; set; }
        public string TotalFabricReced { get; set; }
        public string BeamBalanceMtr { get; set; }
    }
}
