//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientReportingPartyAccountTbl
    {
        public int Id { get; set; }
        public string VerificationName { get; set; }
        public bool Status { get; set; }
        public Nullable<int> PrimaryCustId { get; set; }
    }
}
