//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Details_Tbl
    {
        public int Id { get; set; }
        public string cName { get; set; }
        public string cLogo { get; set; }
        public string cSliderImage1 { get; set; }
        public string cSliderImage2 { get; set; }
        public string cSliderImage3 { get; set; }
        public string cAbout { get; set; }
        public string cAddress { get; set; }
        public string cEmail { get; set; }
        public string cMobile1 { get; set; }
        public string cMobile2 { get; set; }
    }
}
