//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Enqtbl
    {
        public int Id { get; set; }
        public string uname { get; set; }
        public string umob { get; set; }
        public string uemail { get; set; }
        public string usub { get; set; }
        public string umsg { get; set; }
        public string rts { get; set; }
    }
}
