//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSSLLPEntities : DbContext
    {
        public SSSLLPEntities()
            : base("name=SSSLLPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin_Tbl> Admin_Tbl { get; set; }
        public DbSet<CallEnquiry> CallEnquiries { get; set; }
        public DbSet<Color_Tbl> Color_Tbl { get; set; }
        public DbSet<Company_Details_Tbl> Company_Details_Tbl { get; set; }
        public DbSet<Contact_Enqtbl> Contact_Enqtbl { get; set; }
        public DbSet<Customers_Tbl> Customers_Tbl { get; set; }
        public DbSet<Gallery_Tbl> Gallery_Tbl { get; set; }
        public DbSet<MyCart_Tbl> MyCart_Tbl { get; set; }
        public DbSet<Order_Tbl> Order_Tbl { get; set; }
        public DbSet<PageVisit> PageVisits { get; set; }
        public DbSet<Product_Tbl> Product_Tbl { get; set; }
        public DbSet<ProductColorlist> ProductColorlists { get; set; }
        public DbSet<Review_Tbl> Review_Tbl { get; set; }
        public DbSet<ShippingDetail> ShippingDetails { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<ClientReportingPartyAccountTbl> ClientReportingPartyAccountTbls { get; set; }
        public DbSet<ClientReportingTbl> ClientReportingTbls { get; set; }
    }
}
