//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Tbl
    {
        public int Id { get; set; }
        public int CustomerID { get; set; }
        public int ProductID { get; set; }
        public int ShippingID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ColorOrder { get; set; }
        public string OrderColorName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
