//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Tbl
    {
        public int Id { get; set; }
        public string pname { get; set; }
        public string pweight { get; set; }
        public string pdetails { get; set; }
        public string pimg1 { get; set; }
        public string pimg2 { get; set; }
        public string pimg3 { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> rts { get; set; }
    }
}
