//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSSLLP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_Tbl
    {
        public int Id { get; set; }
        public string uname { get; set; }
        public string uimg { get; set; }
        public string ureview { get; set; }
        public string ureviewdate { get; set; }
    }
}
